export const audioTracks = [
  {
    audioId: 'audio001',
    audioSrc: 'I_Hope_She_s_Not_Cold',
    audioTitle: 'I Hope She is Not Cold',
    audioImage: 'album_american_country',
    album: 'American Country',
    artist: 'Andy_Blackwood',
    audioType: '',
  },
  {
    audioId: 'audio002',
    audioSrc: 'I_dance_to_the_Jazz_of_the_50s',
    audioTitle: 'I dance to the Jazz of the 50s',
    audioImage: 'album_I_dance_to_the_Jazz_of_the_50s',
    album: 'I dance to the Jazz of the 50s',
    artist: 'AURBANNIAUDIO',
    audioType: '',
  },
  {
    audioId: 'audio003',
    audioSrc: 'Me_And_Jerry_Reed',
    audioTitle: 'Me And Jerry Reed',
    audioImage: 'album_Me_And_Jerry_Reed',
    album: 'Me And Jerry Reed',
    artist: 'BETP5',
    audioType: '',
  },
  {
    audioId: 'audio004',
    audioSrc: 'Before_You_Break_My_Heart',
    audioTitle: 'Before You Break My Heart',
    audioImage: 'album_Me_And_Jerry_Reed',
    album: 'Me And Jerry Reed',
    artist: 'BETP5',
    audioType: '',
  },
  {
    audioId: 'audio005',
    audioSrc: 'The_imagined_last_day_of_Crawford_Gordon',
    audioTitle: 'The imagined last day of Crawford Gordon',
    audioImage: 'album_The_imagined_last_day_of_Crawford_Gordon',
    album: 'The imagined last day of Crawford Gordon',
    artist: 'BETP5',
    audioType: '',
  },
  {
    audioId: 'audio006',
    audioSrc: 'The_corn_road',
    audioTitle: 'The corn road',
    audioImage: 'album_The_corn_road',
    album: 'The corn road',
    artist: 'FLASHINMUSIC',
    audioType: '',
  },
  {
    audioId: 'audio007',
    audioSrc: 'Madly_Deeply',
    audioTitle: 'Madly Deeply',
    audioImage: 'album_What_Is_Love',
    album: 'What Is Love',
    artist: 'Melanie Ungar',
    audioType: '',
  },
  {
    audioId: 'audio008',
    audioSrc: 'One_Day',
    audioTitle: 'One Day',
    audioImage: 'album_What_Is_Love',
    album: 'What Is Love',
    artist: 'Melanie Ungar',
    audioType: '',
  },
  {
    audioId: 'audio009',
    audioSrc: 'What_Is_Love',
    audioTitle: 'What Is Love',
    audioImage: 'album_What_Is_Love',
    album: 'What Is Love',
    artist: 'Melanie Ungar',
    audioType: '',
  },
  {
    audioId: 'audio010',
    audioSrc: 'French_Kisses_And_Cat_Hair',
    audioTitle: 'French Kisses And Cat Hair',
    audioImage: 'album_Very_Good_Album',
    album: 'Very Good Album',
    artist: 'Michael Ellis',
    audioType: '',
  },
  {
    audioId: 'audio011',
    audioSrc: 'Old_Russian_Waltz_2-Romantic_Piano_Music',
    audioTitle: 'Romantic Piano Music',
    audioImage: 'album_Old_Russian_Waltz',
    album: 'Old Russian Waltz 2',
    artist: 'THE PIANO LADY (LENA ORSA)',
    audioType: 'Piano',
  },
  {
    audioId: 'audio012',
    audioSrc: 'No_Country_Song',
    audioTitle: 'No Country Song',
    audioImage: 'album_High_Tonight',
    album: 'High Tonight',
    artist: 'THEJUNETOMINFLUENCE',
    audioType: 'Rock',
  },
  {
    audioId: 'audio012',
    audioSrc: 'No_Country_Song',
    audioTitle: 'No Country Song',
    audioImage: 'album_High_Tonight',
    album: 'High Tonight',
    artist: 'THEJUNETOMINFLUENCE',
    audioType: 'Rock',
  },
  {
    audioId: 'audio012',
    audioSrc: 'No_Country_Song',
    audioTitle: 'No Country Song',
    audioImage: 'album_High_Tonight',
    album: 'High Tonight',
    artist: 'THEJUNETOMINFLUENCE',
    audioType: 'Rock',
  },
  {
    audioId: 'audio012',
    audioSrc: 'No_Country_Song',
    audioTitle: 'No Country Song',
    audioImage: 'album_High_Tonight',
    album: 'High Tonight',
    artist: 'THEJUNETOMINFLUENCE',
    audioType: 'Rock',
  },
  {
    audioId: 'audio012',
    audioSrc: 'No_Country_Song',
    audioTitle: 'No Country Song',
    audioImage: 'album_High_Tonight',
    album: 'High Tonight',
    artist: 'THEJUNETOMINFLUENCE',
    audioType: 'Rock',
  },
  {
    audioId: 'audio012',
    audioSrc: 'No_Country_Song',
    audioTitle: 'No Country Song',
    audioImage: 'album_High_Tonight',
    album: 'High Tonight',
    artist: 'THEJUNETOMINFLUENCE',
    audioType: 'Rock',
  },
];
