export const zWaveVariants = {
  initial: { scale: 1, y: 30, x: 60, opacity: 1 },
  enter: {
    scale: 1,
    y: 0,
    x: 0,
    opacity: 1,
    transition: { duration: 0.4, ease: [0.48, 0.15, 0.25, 0.96], yoyo: 8 },
  },
  exit: {
    scale: 1,
    y: 0,
    x: 0,
    opacity: 0.6,
    transition: { duration: 0.3, ease: [0.48, 0.15, 0.25, 0.96] },
  },
};

export const toTopVariants = {
  initial: { scale: 1, y: '100vh', opacity: 0.6 },
  enter: {
    scale: 1,
    y: 0,
    opacity: 1,
    transition: { duration: 0.5, ease: [0.48, 0.15, 0.25, 0.96] },
  },
  exit: {
    scale: 1,
    y: '80vh',
    opacity: 0.6,
    transition: { duration: 0.3, ease: [0.48, 0.15, 0.25, 0.96] },
  },
};

export const toBottomVariants = {
  initial: { scale: 1, y: '-100vh', opacity: 0.6 },
  enter: {
    scale: 1,
    y: 0,
    opacity: 1,
    transition: { duration: 0.5, ease: [0.48, 0.15, 0.25, 0.96] },
  },
  exit: {
    scale: 1,
    y: '-80vh',
    opacity: 0.6,
    transition: { duration: 0.3, ease: [0.48, 0.15, 0.25, 0.96] },
  },
};

export const toLeftVariants = {
  initial: { scale: 1, x: '100vh', opacity: 0.5 },
  enter: {
    scale: 1,
    x: 0,
    opacity: 1,
    transition: { duration: 0.5, ease: [0.48, 0.15, 0.25, 0.96] },
  },
  exit: {
    scale: 1,
    x: '40vh',
    opacity: 0,
    transition: { duration: 0.3, ease: [0.48, 0.15, 0.25, 0.96] },
  },
};

export const toRightVariants = {
  initial: { scale: 1, x: '-100vh', opacity: 0.5 },
  enter: {
    scale: 1,
    x: 0,
    opacity: 1,
    transition: { duration: 0.5, ease: [0.48, 0.15, 0.25, 0.96] },
  },
  exit: {
    scale: 1,
    x: '-40vh',
    opacity: 0,
    transition: { duration: 0.3, ease: [0.48, 0.15, 0.25, 0.96] },
  },
};

export const fadeInVariants = {
  initial: { opacity: 0 },
  enter: {
    opacity: 1,
    transition: { duration: 0.3, ease: [0.48, 0.15, 0.25, 0.96] },
  },
  exit: {
    opacity: 0,
    transition: { duration: 0.2, ease: [0.48, 0.15, 0.25, 0.96] },
  },
};

export const MenuItems = [
  {
    label: 'txt-home',
    url: '/',
    icon: '',
    active: true,
  },
  {
    label: 'txt-profile',
    url: '/profile',
    icon: '',
    active: false,
  },
  {
    label: 'txt-price',
    url: '/price',
    icon: '',
    active: false,
  },
  {
    label: 'txt-about',
    url: '/about',
    icon: '',
    active: false,
  },
  // {
  //   label: 'txt-nearby',
  //   url: '/nearby',
  //   icon: '',
  //   active: false,
  // },
  //  {
  //     label: 'Contact',
  //     url: "/contact",
  //     icon: '',
  //     active: true,
  //   },
];

export const myDemoPosts = [
  {
    postId: '13241',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'I_dance_to_the_Jazz_of_the_50s',
      audioTitle: 'I dance to the Jazz of the 50s',
      audioImage: 'album_I_dance_to_the_Jazz_of_the_50s',
      album: 'I dance to the Jazz of the 50s',
      artist: 'AURBANNIAUDIO',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '13214',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'French_Kisses_And_Cat_Hair',
      audioTitle: 'French Kisses And Cat Hair',
      audioImage: 'album_Very_Good_Album',
      album: 'Very Good Album',
      artist: 'Michael Ellis',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },

  {
    postId: '111315',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'event',
    contentObj: {
      contentId: '66253',
      contentTitle: 'A Fantastic Concert',
      contentPhoto: 'e3',
      contentURL: 'string',
      contentType: 'event',
      audioId: '132456gh',
      audioSrc: 'Old_Russian_Waltz_2-Romantic_Piano_Music',
      audioTitle: 'Romantic Piano Music',
      audioImage: 'album_Old_Russian_Waltz',
      album: 'Old Russian Waltz 2',
      artist: 'THE PIANO LADY (LENA ORSA)',
      audioType: 'Piano',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12235',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'The_imagined_last_day_of_Crawford_Gordon',
      audioTitle: 'The imagined last day of Crawford Gordon',
      audioImage: 'album_The_imagined_last_day_of_Crawford_Gordon',
      album: 'The imagined last day of Crawford Gordon',
      artist: 'BETP5',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11135',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'Before_You_Break_My_Heart',
      audioTitle: 'Before You Break My Heart',
      audioImage: 'album_Me_And_Jerry_Reed',
      album: 'Me And Jerry Reed',
      artist: 'BETP5',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12331',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
];
