export const MenuItems = [
  {
    label: 'txt-home',
    url: '/',
    icon: '',
    active: true,
  },
  {
    label: 'txt-profile',
    url: '/profile',
    icon: '',
    active: false,
  },
  {
    label: 'txt-nearby',
    url: '/nearby',
    icon: '',
    active: false,
  },
  //  {
  //     label: 'Contact',
  //     url: "/contact",
  //     icon: '',
  //     active: true,
  //   },
];

export const audioTracks = [
  {
    audioSrc: 'I_Hope_She_s_Not_Cold',
    audioTitle: 'I Hope She is Not Cold',
    audioImage: 'album_american_country',
    album: 'American Country',
    artist: 'Andy_Blackwood',
    audioType: '',
  },
  {
    audioSrc: 'I_dance_to_the_Jazz_of_the_50s',
    audioTitle: 'I dance to the Jazz of the 50s',
    audioImage: 'album_I_dance_to_the_Jazz_of_the_50s',
    album: 'I dance to the Jazz of the 50s',
    artist: 'AURBANNIAUDIO',
    audioType: '',
  },
  {
    audioSrc: 'Me_And_Jerry_Reed',
    audioTitle: 'Me And Jerry Reed',
    audioImage: 'album_Me_And_Jerry_Reed',
    album: 'Me And Jerry Reed',
    artist: 'BETP5',
    audioType: '',
  },
  {
    audioSrc: 'Before_You_Break_My_Heart',
    audioTitle: 'Before You Break My Heart',
    audioImage: 'album_Me_And_Jerry_Reed',
    album: 'Me And Jerry Reed',
    artist: 'BETP5',
    audioType: '',
  },
  {
    audioSrc: 'The_imagined_last_day_of_Crawford_Gordon',
    audioTitle: 'The imagined last day of Crawford Gordon',
    audioImage: 'album_The_imagined_last_day_of_Crawford_Gordon',
    album: 'The imagined last day of Crawford Gordon',
    artist: 'BETP5',
    audioType: '',
  },
  {
    audioSrc: 'The_corn_road',
    audioTitle: 'The corn road',
    audioImage: 'album_The_corn_road',
    album: 'The corn road',
    artist: 'FLASHINMUSIC',
    audioType: '',
  },
  {
    audioSrc: 'Madly_Deeply',
    audioTitle: 'Madly Deeply',
    audioImage: 'album_What_Is_Love',
    album: 'What Is Love',
    artist: 'Melanie Ungar',
    audioType: '',
  },
  {
    audioSrc: 'One_Day',
    audioTitle: 'One Day',
    audioImage: 'album_What_Is_Love',
    album: 'What Is Love',
    artist: 'Melanie Ungar',
    audioType: '',
  },
  {
    audioSrc: 'What_Is_Love',
    audioTitle: 'What Is Love',
    audioImage: 'album_What_Is_Love',
    album: 'What Is Love',
    artist: 'Melanie Ungar',
    audioType: '',
  },
  {
    audioSrc: 'French_Kisses_And_Cat_Hair',
    audioTitle: 'French Kisses And Cat Hair',
    audioImage: 'album_Very_Good_Album',
    album: 'Very Good Album',
    artist: 'Michael Ellis',
    audioType: '',
  },
  {
    audioSrc: 'Old_Russian_Waltz_2-Romantic_Piano_Music',
    audioTitle: 'Romantic Piano Music',
    audioImage: 'album_Old_Russian_Waltz',
    album: 'Old Russian Waltz 2',
    artist: 'THE PIANO LADY (LENA ORSA)',
    audioType: 'Piano',
  },
  {
    audioSrc: 'No_Country_Song',
    audioTitle: 'No Country Song',
    audioImage: 'album_High_Tonight',
    album: 'High Tonight',
    artist: 'THEJUNETOMINFLUENCE',
    audioType: 'Rock',
  },
];
export const demoPosts =[  
{
  postId: 0,
  userId: 0,
  userName: 'Victoria Wirya',
  userAvatar: '',
  postType: 0,
  contentId:0,
  contentTitle: 'American idiot',
  contentPhoto:'',
  contentURL:'',
  isLiked: 0,
  comments:[],
  loading: false,
  error: '',
},
{
  postId: 0,
  userId: 0,
  userName: 'Trang Lê',
  type: 0,
  content: '',
  loading: false,
  error: '',
},
{
  postId: 0,
  userId: 0,
  userName: 'Teco Cheng',
  type: 0,
  content: '',
  loading: false,
  error: '',
},
{
  postId: 0,
  userId: 0,
  userName: '',
  type: 0,
  content: '',
  loading: false,
  error: '',
},
]