export const demoPosts = [
  {
    postId: '11001',
    userId: 'user005',
    userName: 'Taliyah Ruiz',
    userAvatar: '/img/g4.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'One_Day',
      audioTitle: 'One Day',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11002',
    userId: 'user006',
    userName: 'Kelsea Stevenson',
    userAvatar: '/img/g5.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'Before_You_Break_My_Heart',
      audioTitle: 'Before You Break My Heart',
      audioImage: 'album_Me_And_Jerry_Reed',
      album: 'Me And Jerry Reed',
      artist: 'BETP5',
      audioType: '',
    },
    isLiked: 1,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11003',
    userId: 'user007',
    userName: 'Ashley Mill',
    userAvatar: '/img/g6.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'No_Country_Song',
      audioTitle: 'No Country Song',
      audioImage: 'album_High_Tonight',
      album: 'High Tonight',
      artist: 'THEJUNETOMINFLUENCE',
      audioType: 'Rock',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11004',
    userId: 'user004',
    userName: 'Viki Viki',
    userAvatar: '/img/g3.jpg',
    postType: 'event',
    contentObj: {
      contentId: '66253',
      contentTitle: "Jerry's OMG concert",
      contentPhoto: 'e1',
      contentURL: 'string',
      contentType: 'event',
      audioId: '132456gh',
      audioSrc: 'Old_Russian_Waltz_2-Romantic_Piano_Music',
      audioTitle: 'Romantic Piano Music',
      audioImage: 'album_Old_Russian_Waltz',
      album: 'Old Russian Waltz 2',
      artist: 'THE PIANO LADY (LENA ORSA)',
      audioType: 'Piano',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11005',
    userId: 'user009',
    userName: 'Andrew Almond',
    userAvatar: '/img/b1.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'The_corn_road',
      audioTitle: 'The corn road',
      audioImage: 'album_The_corn_road',
      album: 'The corn road',
      artist: 'FLASHINMUSIC',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11006',
    userId: 'user010',
    userName: 'Alton Roberts',
    userAvatar: '/img/b2.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'Old_Russian_Waltz_2-Romantic_Piano_Music',
      audioTitle: 'Romantic Piano Music',
      audioImage: 'album_Old_Russian_Waltz',
      album: 'Old Russian Waltz 2',
      artist: 'THE PIANO LADY (LENA ORSA)',
      audioType: 'Piano',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  
];

export const hiddenDemoPost = [
  {
    postId: '13241',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'I_dance_to_the_Jazz_of_the_50s',
      audioTitle: 'I dance to the Jazz of the 50s',
      audioImage: 'album_I_dance_to_the_Jazz_of_the_50s',
      album: 'I dance to the Jazz of the 50s',
      artist: 'AURBANNIAUDIO',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '13214',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'French_Kisses_And_Cat_Hair',
      audioTitle: 'French Kisses And Cat Hair',
      audioImage: 'album_Very_Good_Album',
      album: 'Very Good Album',
      artist: 'Michael Ellis',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },

  {
    postId: '111315',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'event',
    contentObj: {
      contentId: '66253',
      contentTitle: 'A Fantastic Concert',
      contentPhoto: 'e3',
      contentURL: 'string',
      contentType: 'event',
      audioId: '132456gh',
      audioSrc: 'Old_Russian_Waltz_2-Romantic_Piano_Music',
      audioTitle: 'Romantic Piano Music',
      audioImage: 'album_Old_Russian_Waltz',
      album: 'Old Russian Waltz 2',
      artist: 'THE PIANO LADY (LENA ORSA)',
      audioType: 'Piano',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12235',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'The_imagined_last_day_of_Crawford_Gordon',
      audioTitle: 'The imagined last day of Crawford Gordon',
      audioImage: 'album_The_imagined_last_day_of_Crawford_Gordon',
      album: 'The imagined last day of Crawford Gordon',
      artist: 'BETP5',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11135',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'Before_You_Break_My_Heart',
      audioTitle: 'Before You Break My Heart',
      audioImage: 'album_Me_And_Jerry_Reed',
      album: 'Me And Jerry Reed',
      artist: 'BETP5',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12331',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
]