export const demoPosts = [
  {
    postId: '12345',
    userId: 'user005',
    userName: 'Taliyah Ruiz',
    userAvatar: '/img/g4.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'One_Day',
      audioTitle: 'One Day',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12245',
    userId: 'user006',
    userName: 'Kelsea Stevenson',
    userAvatar: '/img/g5.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'Before_You_Break_My_Heart',
      audioTitle: 'Before You Break My Heart',
      audioImage: 'album_Me_And_Jerry_Reed',
      album: 'Me And Jerry Reed',
      artist: 'BETP5',
      audioType: '',
    },
    isLiked: 1,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '35634',
    userId: 'user007',
    userName: 'Ashley Mill',
    userAvatar: '/img/g6.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'No_Country_Song',
      audioTitle: 'No Country Song',
      audioImage: 'album_High_Tonight',
      album: 'High Tonight',
      artist: 'THEJUNETOMINFLUENCE',
      audioType: 'Rock',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12325',
    userId: 'user004',
    userName: 'Viki Viki',
    userAvatar: '/img/g3.jpg',
    postType: 'event',
    contentObj: {
      contentId: '66253',
      contentTitle: "Jerry's OMG concert",
      contentPhoto: 'e1',
      contentURL: 'string',
      contentType: 'event',
      audioId: '132456gh',
      audioSrc: 'Old_Russian_Waltz_2-Romantic_Piano_Music',
      audioTitle: 'Romantic Piano Music',
      audioImage: 'album_Old_Russian_Waltz',
      album: 'Old Russian Waltz 2',
      artist: 'THE PIANO LADY (LENA ORSA)',
      audioType: 'Piano',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12111',
    userId: 'user009',
    userName: 'Andrew Almond',
    userAvatar: '/img/b1.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'The_corn_road',
      audioTitle: 'The corn road',
      audioImage: 'album_The_corn_road',
      album: 'The corn road',
      artist: 'FLASHINMUSIC',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12326',
    userId: 'user010',
    userName: 'Alton Roberts',
    userAvatar: '/img/b2.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'Old_Russian_Waltz_2-Romantic_Piano_Music',
      audioTitle: 'Romantic Piano Music',
      audioImage: 'album_Old_Russian_Waltz',
      album: 'Old Russian Waltz 2',
      artist: 'THE PIANO LADY (LENA ORSA)',
      audioType: 'Piano',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
];