import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Music body</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-blue-700 text-4xl font-bold py-2 px-4 my-4">
        Next.js + TypeScript + Tailwind
      </div>
     
    </>
  );
};

export default Home;
