import type { NextPage } from 'next';
import Head from 'next/head';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect } from 'react';
import Image from 'next/image';
import { motion } from 'framer-motion';

import Navbar from '../src/components/Navbar';
import ProfileForm from '../src/components/ProfileForm';
import FriendsList from '../src/components/FriendsList';
import PostContent from '../src/components/PostContent';
import { fetchPosts } from '../store/actionCreators/postAction';
import { RootState } from '../store/reducers';
import {
  toTopVariants,
  toLeftVariants,
} from '../common';
import { demoPosts } from '../fakePosts';
import {SideMenu} from '../src/components/SideMenu';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(fetchPosts(demoPosts));
  }, []);

  const postsState = useSelector((state: RootState) => state.postsState);

  return (
    <div className="cs-main-bg-theme relative">
      <Head>
        <title>SameVibes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <SideMenu></SideMenu>
      <div className="container mx-auto overflow-y-auto lg:overflow-y-hidden h-full no-scrollbar">
        <div className="flex-col">
          {/* <ProfileForm/> */}
          <div className="flex flex-col-reverse lg:flex-row justify-between">
            <div className="flex-col lg:w-8/12">
              <div className="lg:cs-post-scroll-height lg:overflow-y-auto no-scrollbar pt-20 pb-20">
                {postsState.posts.map((postItem) => {
                  return (
                    <motion.div
                      key={postItem.postId}
                      className="mb-4"
                      initial="initial"
                      animate="enter"
                      exit="exit"
                      variants={toTopVariants}
                    >
                      <PostContent postItem={postItem} isScrollUp={false} ></PostContent>
                    </motion.div>
                  );
                })}
              </div>
            </div>
            <div className="flex-col lg:w-4/12 h-full pt-4">
              <motion.div
                className="mt-16"
                initial="initial"
                animate="enter"
                exit="exit"
                variants={toLeftVariants}
              >
                <FriendsList></FriendsList>
              </motion.div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
