import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
// import React, { useRef, useState } from 'react';

import Navbar from '../src/components/Navbar';
import ProfileForm from '../src/components/ProfileForm';
import PostContent from '../src/components/PostContent';

const Profile: NextPage = () => {


  return (
    <div className="cs-main-bg-theme pb-8 fixed">
      <Head>
        <title>Music body</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      {/* <nav
        aria-label="Breadcrumb"
        className="cs-navbar-style-light dark:cs-navbar-style-dark flex justify-between px-16 fixed z-10"
      >
        <div className={`${ isStickyNav ? '' : 'hidden' }`}>
          <div className={`text-center my-4 flex flex-row`}>
            <div className="flex items-center mx-2 cs-btn-border-style">
              <FontAwesomeIcon
                icon={['fas', 'user-friends']}
                className="icon-common mr-2"
              ></FontAwesomeIcon>
              <div></div>
              <div className="">Add Friend</div>
            </div>{' '}
            <div className="flex items-center mx-2 cs-btn-border-style">
              <FontAwesomeIcon
                icon={['fas', 'comments']}
                className="icon-common mr-2"
              ></FontAwesomeIcon>
              <div></div>Message
            </div>
          </div>
        </div>
      </nav> */}
      <div
        className="container mx-auto overflow-y-auto h-full no-scrollbar "
      >
        <div className="flex-col pt-4">
          {/* <ProfileForm /> */}
          <div className="cs-block-style-white-theme dark:cs-block-style-grey-900 text-grey-900 dark:text-white mb-4 flex-col">
            <div className="flex flex-col items-center">
              <div className="relative h-32 w-32 2xl:h-40 2xl:w-40 my-4">
                <Image
                  className="rounded-full"
                  src="/img/g2.jpg"
                  alt="me"
                  layout="fill"
                  // width={120}
                  // height={120}
                  objectFit="cover"
                />
              </div>
              <div className="text-center mt-2">Victoria Wirya</div>

              <div className={`text-center my-4 flex flex-row`}>
                <div className="flex items-center mx-2 cs-btn-border-style">
                  <FontAwesomeIcon
                    icon={['fas', 'user-friends']}
                    className="icon-common mr-2"
                  ></FontAwesomeIcon>
                  <div></div>
                  <div className="">Add Friend</div>
                </div>{' '}
                <div className="flex items-center mx-2 cs-btn-border-style">
                  <FontAwesomeIcon
                    icon={['fas', 'comments']}
                    className="icon-common mr-2"
                  ></FontAwesomeIcon>
                  <div></div>Message
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col lg:flex-row justify-between mt-2">
            <div className="flex-col lg:w-5/12">
              <div className="cs-block-style-white-theme dark:cs-block-style-grey-900">
                <div className="text-center w-80 mt-4">
                  My name is Victoria Wirya, and I am a recent computer science
                  graduate from Stanford University.
                </div>
              </div>
              <div className="cs-block-style-white-theme dark:cs-block-style-grey-900">
                <div className="flex flex-col p-4">
                  <div className="flex items-center">
                    <FontAwesomeIcon
                      icon={['fas', 'briefcase']}
                      className="icon-common mr-2"
                    ></FontAwesomeIcon>
                    <div></div>Work
                  </div>{' '}
                  <div className="flex items-center">
                    <FontAwesomeIcon
                      icon={['fas', 'graduation-cap']}
                      className="icon-common mr-2"
                    ></FontAwesomeIcon>
                    <div></div>School
                  </div>{' '}
                  <div className="flex items-center">
                    <FontAwesomeIcon
                      icon={['fas', 'map-marker-alt']}
                      className="icon-common mr-2"
                    ></FontAwesomeIcon>
                    <div></div>Living
                  </div>{' '}
                  <div className="flex items-center">
                    <FontAwesomeIcon
                      icon={['fab', 'instagram']}
                      className="icon-common mr-2"
                    ></FontAwesomeIcon>
                    <div></div>Instagram
                  </div>
                  <div className="flex items-center">
                    <FontAwesomeIcon
                      icon={['fas', 'heart']}
                      className="icon-common mr-2"
                    ></FontAwesomeIcon>
                    <div></div>Single
                  </div>
                </div>
              </div>
              <div className="cs-block-style-white-theme dark:cs-block-style-grey-900 mt-4">
                <div className="flex flex-col p-4">
                  <div>Favorite Albums</div>
                  <div>
                    <div className="grid gap-4 grid-cols-3 grid-rows-3 mt-4">
                      {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((item, i) => {
                        return (
                          <div
                            key={i}
                            className="relative min-w-min aspect-square"
                          >
                            <Image
                              className="rounded-md"
                              src="/img/album-01.jpg"
                              alt="me"
                              layout="fill"
                              // width={120}
                              // height={120}
                              objectFit="cover"
                            />
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex-col lg:w-7/12 mt-4 lg:mt-0 lg:ml-4 mb-8">
              <div className="cs-block-style-white-theme dark:cs-block-style-grey-900">
                <div className="flex flex-col">
                  <div className="p-4">Posts</div>
                  <div className="mb-4 px-4">
                    <PostContent></PostContent>
                  </div>
                  <div className="mb-4 px-4">
                    <PostContent></PostContent>
                  </div>{' '}
                  <div className="mb-4 px-4">
                    <PostContent></PostContent>
                  </div>{' '}
                  <div className="mb-4 px-4">
                    <PostContent></PostContent>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Profile;
