import type { NextPage } from 'next';
import Head from 'next/head';
import { useDispatch, useSelector } from 'react-redux';
import {useEffect} from 'react';

import Navbar from '../src/components/Navbar';
import User from '../src/components/User';
import {getCurUser} from '../store/actionCreators/userAction';
import { RootState } from '../store/reducers';
import {SideMenu} from '../src/components/SideMenu';

const Profile: NextPage = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getCurUser('user001'));
  }, []);

  const curUserProfile = useSelector((state: RootState) => state.userReducer.curUser);
  return (
    <div className="cs-main-bg-theme">
      <Head>
        <title>SameVibes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <SideMenu></SideMenu>
      <User userProfile={curUserProfile} isScrollUp={true} isProfile={true}></User>
    </div>
  );
};

export default Profile;
