import type { NextPage } from 'next';
import Head from 'next/head';

import Navbar from '../src/components/Navbar';



const User: NextPage = () => {

  return (
    <div className="cs-main-bg-theme fixed">
      <Head>
        <title>Same Vibes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <div className="container mx-auto overflow-y-auto lg:overflow-y-hidden h-full no-scrollbar">
        
      </div>
    </div>
  );
};

export default User;
